import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Leftbar from '@/components/Leftbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='flex'>
          <Leftbar />
          <section className='w-full'>
            <div className='p-5'>
              {children}
            </div>
          </section> 
        </main>
      </body>
    </html>
  )
}
